version: '3'

services:
  web-nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
    ports:
      - 9000:9000

