version: '2'

networks:
  laravel-nginx:
    external: true

services:
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./www:/var/www
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
#      - ./log:/var/log/nginx
    ports:
      - 8080:80
    links:
      - php-fpm
    networks:
      - laravel-nginx

  php-fpm:
    build:
      context: ./.docker/php
      dockerfile: ./Dockerfile
    volumes:
      - ./www:/var/www
#      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
#      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 9000:9000
    links:
      - mysql
    networks:
      - laravel-nginx
    environment:
      DB_HOST: mysql
      DB_DATABASE: test_db
      DB_USERNAME: app
      DB_PASSWORD: secret

  mysql:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306
    networks:
      - laravel-nginx
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
