version: '3'

services:
  web-nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
    links:
      - mysql
    ports:
      - 9000:9000
    environment:
      DB_HOST: mysql
      DB_DATABASE: test_db
      DB_USERNAME: app
      DB_PASSWORD: secret
  mysql:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

