version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-php-apache2
    ports:
      - 8080:80
    volumes:
      - ./code:/var/www/html
    environment:
      DB_HOST: mysql
